version: '3'
services:
        webclient:
                image: "srswinde/indi_webclient"
                ports: 
                        - "3000:3000"
                environment:
                        - INDISERVER=localhost
                
                network_mode: "host"

        nginx-server:
                image: "nginx"
                ports:
                        - "4001:80"
                        - "3001:3000"
                volumes:
                        - "./www:/usr/share/nginx/html"
                #network_mode: "host"

        
        indidriver:
                image: "srswinde/indidrivers"
                ports:
                        - "7624:7624"
                environment:
                        - INDIDRVCFG=/conf/kuiper.conf
                network_mode: "host"
                command:
                        /usr/bin/indiserver  -v /driverbin/tcs-indi /driverbin/dome-indi /driverbin/focus-indi /driverbin/snooper
#
#        browser:
#                image: "srswinde/firefox"
#                volumes:
#                        - "/tmp/.X11-unix:/tmp/.X11-unix"
#                environment:
#                        - DISPLAY=unix$DISPLAY
#                command:
#                        /usr/bin/chromium-browser /usr/bin/chromium-browser --no-sandbox --app=http://localhost/tcs.html
#                network_mode: "host"
#
#
#        xephem:
#                image: "srswinde/xephem"
#                volumes:
#                        - "${HOME}/.xephem:/home/developer/.xephem"
#                        - "/tmp/.X11-unix:/tmp/.X11-unix"
#                environment:
#                        - DISPLAY=$DISPLAY
#                        - HOME=/home/developer
#                network_mode: "host"
#                depends_on:
#                        - browser
#
